name: symphia
description: "Personalize AI Companion"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  audio_wave: ^0.1.5
  characters: ^1.3.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.7.1
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  get: ^4.6.6
  google_generative_ai: ^0.4.0
  google_sign_in: ^6.2.1
  html: ^0.15.4
  intl: ^0.19.0
  permission_handler: ^11.3.1
  speech_to_text: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - .env

flutter_launcher_icons:
 image_path: "assets/images/symphia-colored-logo.png"
 android: true
 ios: true