// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['WEB_API_KEY']!,
        appId: dotenv.env['WEB_APP_ID']!,
        messagingSenderId: '455133580821',
        projectId: 'symphia',
        authDomain: 'symphia.firebaseapp.com',
        storageBucket: 'symphia.appspot.com',
        measurementId: 'G-VQN0PE5TWT',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['ANDROID_API_KEY']!,
        appId: dotenv.env['ANDROID_APP_ID']!,
        messagingSenderId: '455133580821',
        projectId: 'symphia',
        storageBucket: 'symphia.appspot.com',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['IOS_API_KEY']!,
        appId: dotenv.env['IOS_APP_ID']!,
        messagingSenderId: '455133580821',
        projectId: 'symphia',
        storageBucket: 'symphia.appspot.com',
        iosClientId:
            '455133580821-4l49f00e5ple1fu5t2ufbuhvacpeec4l.apps.googleusercontent.com',
        iosBundleId: 'com.example.symphia',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['MACOS_API_KEY']!,
        appId: dotenv.env['MACOS_APP_ID']!,
        messagingSenderId: '455133580821',
        projectId: 'symphia',
        storageBucket: 'symphia.appspot.com',
        iosClientId:
            '455133580821-4l49f00e5ple1fu5t2ufbuhvacpeec4l.apps.googleusercontent.com',
        iosBundleId: 'com.example.symphia',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['WINDOWS_API_KEY']!,
        appId: dotenv.env['WINDOWS_APP_ID']!,
        messagingSenderId: '455133580821',
        projectId: 'symphia',
        authDomain: 'symphia.firebaseapp.com',
        storageBucket: 'symphia.appspot.com',
        measurementId: 'G-BR9WZXGLMZ',
      );
}
