// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF2b2z5B1sgEh74rg8q4Tap7PStU47xDs',
    appId: '1:455133580821:web:7e591243322a40e528481c',
    messagingSenderId: '455133580821',
    projectId: 'symphia',
    authDomain: 'symphia.firebaseapp.com',
    storageBucket: 'symphia.appspot.com',
    measurementId: 'G-VQN0PE5TWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzpvyZi85hdlz6W-n0nCLJoryFfEAh9rM',
    appId: '1:455133580821:android:4b7472bdc702b56e28481c',
    messagingSenderId: '455133580821',
    projectId: 'symphia',
    storageBucket: 'symphia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmm7TKWGjy_yum5VWFEw4Xal1A9qUII1I',
    appId: '1:455133580821:ios:4c37430028cbe16428481c',
    messagingSenderId: '455133580821',
    projectId: 'symphia',
    storageBucket: 'symphia.appspot.com',
    iosClientId: '455133580821-4l49f00e5ple1fu5t2ufbuhvacpeec4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.symphia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmm7TKWGjy_yum5VWFEw4Xal1A9qUII1I',
    appId: '1:455133580821:ios:4c37430028cbe16428481c',
    messagingSenderId: '455133580821',
    projectId: 'symphia',
    storageBucket: 'symphia.appspot.com',
    iosClientId: '455133580821-4l49f00e5ple1fu5t2ufbuhvacpeec4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.symphia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF2b2z5B1sgEh74rg8q4Tap7PStU47xDs',
    appId: '1:455133580821:web:a5b057adf010e8f228481c',
    messagingSenderId: '455133580821',
    projectId: 'symphia',
    authDomain: 'symphia.firebaseapp.com',
    storageBucket: 'symphia.appspot.com',
    measurementId: 'G-BR9WZXGLMZ',
  );
}
